server.port=8181
spring.application.name=tool-calling-example
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini

logging.level.org.springframework.ai.chat.client.advisor=DEBUG

app.weather.api-key=70eda467c1494dd992a151714250406
